// <auto-generated />
using System;
using KHENSYS.HRMANAGER.PERSISTENCE;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace KHENSYS.HRMANAGER.PERSISTENCE.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230322045815_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("KHENSYS.HRMANAGER.DOMAIN.Entities.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("EmployeeLastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PermissionTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("RequestDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PermissionTypeId");

                    b.ToTable("Permissions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EmployeeLastName = "Albuez",
                            EmployeeName = "Abel",
                            PermissionTypeId = 1,
                            RequestDate = new DateTime(2023, 3, 22, 0, 58, 14, 938, DateTimeKind.Local).AddTicks(787)
                        });
                });

            modelBuilder.Entity("KHENSYS.HRMANAGER.DOMAIN.Entities.PermissionType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PermissionTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Enfermedad"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Diligencias"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Familia"
                        });
                });

            modelBuilder.Entity("KHENSYS.HRMANAGER.DOMAIN.Entities.Permission", b =>
                {
                    b.HasOne("KHENSYS.HRMANAGER.DOMAIN.Entities.PermissionType", "PermissionType")
                        .WithMany("Permission")
                        .HasForeignKey("PermissionTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
